export const DEMO_TRENDS_EARLY = [
  {
    id: 'trend-early-1',
    title: 'AI Meeting Notes for Niche Teams',
    summary: 'Small remote teams are looking for lightweight, role-aware meeting summaries and action extraction.',
    opportunityScore: 82,
    velocityGrowth: 0.42,
    problemIntensity: 0.78,
    discussionVolume: 186,
    noveltyScore: 0.64,
    status: 'EMERGING',
    stage: 'early_signal',
    firstDetected: '2026-03-08T10:00:00.000Z',
    lastUpdated: '2026-03-23T09:15:00.000Z',
    growthRate: 0.36,
    momentum: 'accelerating',
    suggestedIdeas: ['Slack-native AI recap bot', 'Meeting quality scorecard', 'Follow-up auto-drafter'],
    targetAudience: 'Remote startup teams (5-40 people)',
    marketPotential: 'Medium',
    keywords: ['meeting notes', 'ai summary', 'team productivity'],
  },
  {
    id: 'trend-early-2',
    title: 'No-Code Customer Onboarding Checklists',
    summary: 'Founders want configurable onboarding flows without building full product tours from scratch.',
    opportunityScore: 74,
    velocityGrowth: 0.31,
    problemIntensity: 0.71,
    discussionVolume: 142,
    noveltyScore: 0.58,
    status: 'EMERGING',
    stage: 'early_signal',
    firstDetected: '2026-03-03T11:00:00.000Z',
    lastUpdated: '2026-03-23T08:25:00.000Z',
    growthRate: 0.27,
    momentum: 'stable',
    suggestedIdeas: ['Template marketplace for onboarding', 'In-app checklist widget', 'Onboarding analytics starter kit'],
    targetAudience: 'SaaS founders and PMs',
    marketPotential: 'Medium',
    keywords: ['onboarding', 'no-code', 'saas growth'],
  },
  {
    id: 'trend-early-3',
    title: 'AI-Powered Technical Content Repurposing',
    summary: 'Developers are asking for tools to convert one long technical post into platform-specific short formats.',
    opportunityScore: 79,
    velocityGrowth: 0.38,
    problemIntensity: 0.69,
    discussionVolume: 165,
    noveltyScore: 0.62,
    status: 'VALIDATED',
    stage: 'early_signal',
    firstDetected: '2026-02-28T13:40:00.000Z',
    lastUpdated: '2026-03-23T10:05:00.000Z',
    growthRate: 0.33,
    momentum: 'accelerating',
    suggestedIdeas: ['Markdown-to-social thread transformer', 'Tone presets for technical audiences'],
    targetAudience: 'Indie hackers and developer advocates',
    marketPotential: 'High',
    keywords: ['content repurposing', 'developer marketing', 'ai writing'],
  },
]

export const DEMO_TRENDS_EXPLODING = [
  {
    id: 'trend-exploding-1',
    title: 'Vertical AI Agents for Support Ops',
    summary: 'Operations teams are rapidly adopting domain-specific AI agents with strict workflow constraints.',
    opportunityScore: 91,
    velocityGrowth: 0.81,
    problemIntensity: 0.83,
    discussionVolume: 412,
    noveltyScore: 0.71,
    status: 'VALIDATED',
    stage: 'exploding',
    firstDetected: '2026-02-01T08:00:00.000Z',
    lastUpdated: '2026-03-23T09:50:00.000Z',
    growthRate: 0.74,
    momentum: 'accelerating',
    suggestedIdeas: ['Agent QA dashboard', 'Escalation policy builder', 'Human-in-loop assistant'],
    targetAudience: 'Support and operations leads',
    marketPotential: 'High',
    keywords: ['ai agents', 'customer support', 'operations'],
  },
  {
    id: 'trend-exploding-2',
    title: 'Lightweight Internal Tool Marketplaces',
    summary: 'SMBs are creating curated internal app catalogs to speed up approved tool adoption.',
    opportunityScore: 86,
    velocityGrowth: 0.67,
    problemIntensity: 0.72,
    discussionVolume: 338,
    noveltyScore: 0.59,
    status: 'VALIDATED',
    stage: 'exploding',
    firstDetected: '2026-01-22T09:30:00.000Z',
    lastUpdated: '2026-03-23T07:42:00.000Z',
    growthRate: 0.63,
    momentum: 'accelerating',
    suggestedIdeas: ['Internal app governance tool', 'Tool request workflow engine'],
    targetAudience: 'IT admins and revops teams',
    marketPotential: 'High',
    keywords: ['internal tools', 'it governance', 'marketplace'],
  },
  {
    id: 'trend-exploding-3',
    title: 'Real-Time Pricing Intelligence for Micro-SaaS',
    summary: 'Founders are actively benchmarking competitor price changes with alert-driven workflows.',
    opportunityScore: 84,
    velocityGrowth: 0.62,
    problemIntensity: 0.68,
    discussionVolume: 291,
    noveltyScore: 0.57,
    status: 'EMERGING',
    stage: 'exploding',
    firstDetected: '2026-01-29T14:15:00.000Z',
    lastUpdated: '2026-03-23T10:12:00.000Z',
    growthRate: 0.55,
    momentum: 'stable',
    suggestedIdeas: ['Competitor pricing snapshots', 'Price-page diff alerts'],
    targetAudience: 'Micro-SaaS founders',
    marketPotential: 'Medium',
    keywords: ['pricing intelligence', 'saas analytics', 'competitive research'],
  },
]

export const DEMO_OPPORTUNITY_MAP = {
  items: [
    {
      id: 'opp-1',
      title: 'Support Agent QA Console',
      keywords: ['ai agents', 'support', 'quality assurance'],
      opportunityScore: 89,
      velocityGrowth: 0.73,
      problemIntensity: 0.82,
      discussionVolume: 264,
      stage: 'exploding',
      postCount: 48,
    },
    {
      id: 'opp-2',
      title: 'Onboarding Checklist Generator',
      keywords: ['onboarding', 'no-code', 'retention'],
      opportunityScore: 77,
      velocityGrowth: 0.35,
      problemIntensity: 0.76,
      discussionVolume: 156,
      stage: 'early_signal',
      postCount: 33,
    },
    {
      id: 'opp-3',
      title: 'Dev Content Transformer',
      keywords: ['content', 'developer marketing', 'automation'],
      opportunityScore: 80,
      velocityGrowth: 0.57,
      problemIntensity: 0.66,
      discussionVolume: 188,
      stage: 'emerging',
      postCount: 40,
    },
    {
      id: 'opp-4',
      title: 'Internal Tool Approval Flow',
      keywords: ['it governance', 'workflow', 'security'],
      opportunityScore: 72,
      velocityGrowth: 0.48,
      problemIntensity: 0.44,
      discussionVolume: 121,
      stage: 'emerging',
      postCount: 21,
    },
  ],
  quadrants: {
    quickWins: [
      {
        id: 'opp-2',
        title: 'Onboarding Checklist Generator',
        keywords: ['onboarding', 'no-code', 'retention'],
        opportunityScore: 77,
        velocityGrowth: 0.35,
        problemIntensity: 0.76,
        discussionVolume: 156,
        stage: 'early_signal',
        postCount: 33,
      },
    ],
    bigBets: [
      {
        id: 'opp-1',
        title: 'Support Agent QA Console',
        keywords: ['ai agents', 'support', 'quality assurance'],
        opportunityScore: 89,
        velocityGrowth: 0.73,
        problemIntensity: 0.82,
        discussionVolume: 264,
        stage: 'exploding',
        postCount: 48,
      },
      {
        id: 'opp-3',
        title: 'Dev Content Transformer',
        keywords: ['content', 'developer marketing', 'automation'],
        opportunityScore: 80,
        velocityGrowth: 0.57,
        problemIntensity: 0.66,
        discussionVolume: 188,
        stage: 'emerging',
        postCount: 40,
      },
    ],
    fillIns: [
      {
        id: 'opp-4',
        title: 'Internal Tool Approval Flow',
        keywords: ['it governance', 'workflow', 'security'],
        opportunityScore: 72,
        velocityGrowth: 0.48,
        problemIntensity: 0.44,
        discussionVolume: 121,
        stage: 'emerging',
        postCount: 21,
      },
    ],
    hardSlogs: [],
  },
  summary: {
    total: 4,
    byStage: {
      early_signal: 1,
      emerging: 2,
      exploding: 1,
    },
    avgOpportunityScore: 79.5,
  },
}

export const DEMO_QUICK_WINS = DEMO_OPPORTUNITY_MAP.quadrants.quickWins

export const DEMO_INSIGHTS = {
  topQuickWin: DEMO_OPPORTUNITY_MAP.quadrants.quickWins[0] || null,
  topBigBet: DEMO_OPPORTUNITY_MAP.quadrants.bigBets[0] || null,
  mostDiscussed: DEMO_OPPORTUNITY_MAP.items
    .slice()
    .sort((a, b) => b.discussionVolume - a.discussionVolume)[0] || null,
  fastestGrowing: DEMO_OPPORTUNITY_MAP.items
    .slice()
    .sort((a, b) => b.velocityGrowth - a.velocityGrowth)[0] || null,
  recommendations: [
    'Ship a narrow MVP in the quick-win segment to validate pricing fast.',
    'Prioritize opportunities where pain intensity exceeds 70%.',
    'Use weekly velocity tracking to catch breakout demand early.',
  ],
}
